services:
  web:
    container_name: web
    image: smunity/web:latest
    build:
      context: .
    environment:
      CADDY_EMAIL: ${CADDY_EMAIL}
      BACKEND_HOST: ${BACKEND_HOST}
      GRAFANA_HOST: ${GRAFANA_HOST}
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks: [ smunity ]
    restart: always

volumes:
  caddy_data:
  caddy_config:

networks:
  smunity:
    external: true
