services:
  smunity:
    build:
      context: .
      args:
        BACKEND_HOST: host.docker.internal:8080
    container_name: smunity-web
    restart: always
    ports:
      - "80:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
