services:
  web:
    container_name: smunity-web-dev
    image: ghcr.io/smu-nity/smunity-web:latest
    build: .
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-host.docker.internal:8080}
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile:ro
    ports:
      - "80:80"
    restart: always
