services:
  web:
    container_name: smunity-web
    image: ${IMAGE}
    environment:
      BACKEND_HOST: ${BACKEND_HOST}
      GRAFANA_HOST: ${GRAFANA_HOST}
    ports:
      - "80:80"
    networks: [ smunity ]
    restart: always

networks:
  smunity:
    external: true
