services:
  web:
    container_name: smunity-web-dev
    image: ghcr.io/smu-nity/smunity-web:latest
    build: .
    platform: linux/amd64
    environment:
      BACKEND_HOST: ${BACKEND_HOST:-host.docker.internal:8080}
      GRAFANA_HOST: ${GRAFANA_HOST:-host.docker.internal:3000}
    ports:
      - "80:80"
    restart: always
